### ISSUE TITLE
Canonicalize a graph?

### ISSUE THREAD

**Issue by alexgleason** [rdf-elixir/rdf-ex#11]
In Ruby, it is possible to get a string of a canonicalized graph like this (code from Mastodon):

```ruby
  def canonicalize(json)
    graph = RDF::Graph.new << JSON::LD::API.toRdf(json, documentLoader: method(:load_jsonld_context))
    graph.dump(:normalize)
  end
```

I'm trying to do something similar in Elixir to verify JSON-LD signatures in ActivityPub.

I guess `:normalize` would be a serialization format. Is this library able to do it at this time?

**Comment by marcelotto** [comment]
If I remember correctly, RDF.rb has an implementation of the [RDF dataset canonicalization spec](https://json-ld.github.io/rdf-dataset-canonicalization/spec/), which I suppose will be used with this flag. In fact I've started working on an implementation of this spec for RDF.ex a couple years ago too, but didn't finish it back then and don't have time to finish it at the moment. 

If you're really willing to finish it, I can push the branch, but you should be warned by this statement from the spec:
> This document is a detailed specification for an RDF dataset canonicalization algorithm. The document is primarily intended for the following audiences:
>
> - Software developers that want to implement an RDF dataset canonicalization algorithm.
> - Masochists.

And as quite some time has passed since my attempt, I'm not into the code anymore and can't help that much.

**Comment by alexgleason** [comment]
Thank you for your advice, I appreciate it. I'm not sure I'm brave enough to implement it myself. What I'm really trying to do is develop federated Groups in ActivityPub, and I need a way to validate private objects. The Group wraps the original JSON-LD object with more metadata before sending it out to its members, and I need to verify the authenticity of the original object while being unable to refetch it.

Thank you again for your time. I might need to look into other ways of doing this.

**Comment by marcelotto** [comment]
@alexgleason Probably too late for you, but for the sake of completeness: you can now achieve this with the RDF Dataset Canonicalization implementation released today with RDF.ex 1.1:

```elixir
graph
|> RDF.Dataset.canonicalize()
|> RDF.NQuads.write_string()
```
