### ISSUE TITLE
Trying to load the schema.org vocabulary results in an error

### ISSUE THREAD

**Issue by carlotm** [rdf-elixir/rdf-ex#22]
Hi,

I am trying to load the schema.org ttl using this code:

```
defmodule Foo.SchemaOrg do
  use RDF.Vocabulary.Namespace

  defvocab EX,
    base_iri: "https://schema.org/",
    file: "schemaorg-current-https.ttl",
    ignore: [:"3DModel"]
end
``` 

I am getting this error:

```
x mix compile
Compiling 1 file (.ex)
warning: 'https://schema.org/source' is a lowercased non-property resource
  (rdf 2.0.1) lib/rdf/vocabulary/namespace/case_validation.ex:135: anonymous fn/4 in RDF.Vocabulary.Namespace.CaseValidation.do_handle_case_violations/3
  (elixir 1.17.3) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
  (stdlib 4.3.1.5) maps.erl:411: :maps.fold_1/3
  (rdf 2.0.1) lib/rdf/vocabulary/namespace/case_validation.ex:133: RDF.Vocabulary.Namespace.CaseValidation.do_handle_case_violations/3
  (rdf 2.0.1) lib/rdf/vocabulary/namespace/term_mapping.ex:72: RDF.Vocabulary.Namespace.TermMapping.new/5
  (rdf 2.0.1) lib/rdf/vocabulary/namespace/vocabulary_namespace.ex:224: RDF.Vocabulary.Namespace.create/5

Compiling lib/foo.schemaorg.ex (it's taking more than 10s)

== Compilation error in file lib/foo.schemaorg.ex ==
** (CompileError) elixir_compiler_3:1: function '__MODULE__'/1+14:
  An implementation limit was reached.
  Try reducing the complexity of this function.

  Instruction: {call_ext,5,{extfunc,'Elixir.Module','__put_attribute__',5}}

    (stdlib 4.3.1.5) lists.erl:1442: :lists.foreach_1/2
```

I took the ttl file from:
 https://github.com/schemaorg/schemaorg/tree/main/data/releases/28.0

Thank you
Cheers

**Comment by marcelotto** [comment]
Since I was able to successfully define earlier versions of the Schema.org vocabulary as `RDF.Vocabulary.Namespace`, but am seeing this error for the first time, it appears that newer versions have grown to a size where we're hitting an Erlang implementation limit. Unfortunately, I don't see a quick fix to work around this limitation. I'll try to dive deeper into the current implementation of `RDF.Vocabulary.Namespace`s in the coming days to find ways to circumvent this limitation.

In the meantime, a possible workaround would be to forgo the compile-time checks and define the vocabulary as a non-strict vocabulary:

```elixir
defmodule Foo.NS do
  use RDF.Vocabulary.Namespace

  defvocab SchemaOrg,
    base_iri: "https://schema.org/",
    terms: [], 
    strict: false
end
```

This at least allows you to use namespace terms like `SchemaOrg.Person` and `SchemaOrg.name()` in your code. You'll just need to ensure correct spelling yourself since you won't have compile-time validation.

**Comment by carlotm** [comment]
@marcelotto ok, fair enough. Thank you!

**Comment by marcelotto** [comment]
The issue has now been fixed.

Also, the case violation warning you encountered ("'https://schema.org/source' is a lowercased non-property resource") was incorrect and has been fixed as well. With the latest version, the vocabulary namespace should be generated without any errors or warnings.

Until the next release, you can use the master version by adding this to your mix.deps:

```elixir
{:rdf, github: "rdf-elixir/rdf-ex"}
```

Let me know if you run into any other issues!

**Comment by carlotm** [comment]
@marcelotto Amazing, Thank you!
